import { randomUUID } from "node:crypto";

export function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72);
}

function yamlScalar(value) {
  if (value === undefined || value === null) return "\"\"";
  const text = String(value);
  if (!text) return "\"\"";
  if (/^[A-Za-z0-9][A-Za-z0-9 .:/?&=_#%+@,()-]*$/.test(text) && !text.includes(": ")) return text;
  return JSON.stringify(text);
}

function yamlList(values, indent) {
  if (!Array.isArray(values) || !values.length) return [`${indent}[]`];
  return values.map((value) => `${indent}- ${yamlScalar(value)}`);
}

export function catalogToServicesYaml(catalog) {
  const lines = [
    "# Generated by Landingpage. Edit this file in GitHub or in the Landingpage UI.",
    "# The x-landingpage block stores searchable metadata for the tool.",
    ""
  ];

  for (const page of catalog.pages || []) {
    lines.push(`- ${yamlScalar(page.name)}:`);
    for (const service of page.services || []) {
      lines.push(`    - ${yamlScalar(service.name)}:`);
      lines.push(`        href: ${yamlScalar(service.href)}`);
      if (service.description) lines.push(`        description: ${yamlScalar(service.description)}`);
      if (service.icon) lines.push(`        icon: ${yamlScalar(service.icon)}`);
      if (service.widgetType) {
        lines.push("        widget:");
        lines.push(`          type: ${yamlScalar(service.widgetType)}`);
      }
      lines.push("        x-landingpage:");
      lines.push(`          id: ${yamlScalar(service.id || slugify(service.name))}`);
      if (service.category) lines.push(`          category: ${yamlScalar(service.category)}`);
      if (service.notes) lines.push(`          notes: ${yamlScalar(service.notes)}`);
      lines.push("          tags:");
      lines.push(...yamlList(service.tags || [page.name], "            "));
      lines.push("          keywords:");
      lines.push(...yamlList(service.keywords || [], "            "));
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function parseScalar(raw = "") {
  const value = raw.trim();
  if (!value || value === "[]") return value === "[]" ? [] : "";
  if ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'"))) {
    try {
      return JSON.parse(value);
    } catch {
      return value.slice(1, -1);
    }
  }
  return value;
}

function ensureLanding(service) {
  service.tags ||= [];
  service.keywords ||= [];
}

export function servicesYamlToCatalog(text, previous = {}) {
  const catalog = {
    meta: {
      title: previous.meta?.title || "Landingpage",
      source: "Imported from data/services.yaml",
      updatedAt: new Date().toISOString()
    },
    pages: []
  };
  let page = null;
  let service = null;
  let section = null;
  let listTarget = null;

  for (const line of text.split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;

    const pageMatch = line.match(/^- (.+):\s*$/);
    if (pageMatch) {
      const name = parseScalar(pageMatch[1]);
      page = {
        id: slugify(name) || `page-${randomUUID().slice(0, 8)}`,
        name,
        description: previous.pages?.find((item) => item.name === name)?.description || "Synced from services.yaml",
        services: []
      };
      catalog.pages.push(page);
      service = null;
      section = null;
      listTarget = null;
      continue;
    }

    const serviceMatch = line.match(/^    - (.+):\s*$/);
    if (serviceMatch && page) {
      const name = parseScalar(serviceMatch[1]);
      service = {
        id: slugify(name) || `service-${randomUUID().slice(0, 8)}`,
        name,
        href: "",
        description: "",
        icon: "",
        tags: [page.name],
        category: page.name,
        keywords: [],
        notes: ""
      };
      page.services.push(service);
      section = null;
      listTarget = null;
      continue;
    }

    if (!service) continue;

    const topProp = line.match(/^        ([A-Za-z0-9_-]+):(?:\s*(.*))?$/);
    if (topProp) {
      const [, key, rawValue = ""] = topProp;
      section = key;
      listTarget = null;
      if (key === "href" || key === "description" || key === "icon") service[key] = parseScalar(rawValue);
      continue;
    }

    const widgetProp = line.match(/^          type:\s*(.*)$/);
    if (section === "widget" && widgetProp) {
      service.widgetType = parseScalar(widgetProp[1]);
      continue;
    }

    const metaProp = line.match(/^          ([A-Za-z0-9_-]+):(?:\s*(.*))?$/);
    if (section === "x-landingpage" && metaProp) {
      const [, key, rawValue = ""] = metaProp;
      if (key === "tags" || key === "keywords") {
        ensureLanding(service);
        service[key] = [];
        listTarget = key;
      } else {
        service[key] = parseScalar(rawValue);
        listTarget = null;
      }
      continue;
    }

    const listValue = line.match(/^            -\s*(.*)$/);
    if (section === "x-landingpage" && listTarget && listValue) {
      ensureLanding(service);
      service[listTarget].push(parseScalar(listValue[1]));
    }
  }

  return catalog;
}
